on:
  push:
    branches:
      - "**"

name: Build
env:
  GO_VERSION: 1.23

jobs:
  build:
    name: Run checks and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{env.GO_VERSION}}

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{env.GO_VERSION}}

      - run: go fmt ./...