name: Release
# on:
#   push:
#     tags: [ v* ]
on:
  push:
    branches:
      - "**"
      
env:
  GO_VERSION: 1.23
  REPO: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        GOOS: [linux, darwin, windows]
        GOARCH: [amd64, arm64]
        include:
          - GOOS: windows
            ext: .exe
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Repo Name
      id: repo-name
      run: echo name=$(basename ${{ github.repository }}) >> $GITHUB_OUTPUT

    - name: Test
      run: go test -v ./...

    - name: Build
      run: make package PROGRAM=${{ env.GOOS }}-${{ env.GOARCH }}/${{ steps.repo-name.outputs.name }}${{ matrix.ext }} PACKAGE=dist/${{ steps.repo-name.outputs.name }}-${{ matrix.GOOS }}-${{ matrix.GOARCH }}.zip
      env:
        GOOS: ${{ matrix.GOOS }}
        GOARCH: ${{ matrix.GOARCH }}

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: artifacts-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
        path: dist
        retention-days: 1
        if-no-files-found: error